---
output: hugodown::hugo_document

slug: haven-2-5-0
title: haven 2.5.0
date: 2022-04-18
author: Hadley Wickham
description: >
  haven 2.5.0 adds support for custom character widths, creates FDA-compliant
  XPT files, and can use Stata's `strL` variable type.
photo:
  url: https://unsplash.com/photos/VsPsf4F5Pi0
  author: Nathan Jennings

# one of: "deep-dive", "learn", "package", "programming", "roundup", or "other"
categories: [package] 
tags: [haven]
---

<!--
TODO:
* [x] Look over / edit the post's title in the yaml
* [x] Edit (or delete) the description; note this appears in the Twitter card
* [x] Pick category and tags (see existing with `hugodown::tidy_show_meta()`)
* [x] Find photo & update yaml metadata
* [x] Create `thumbnail-sq.jpg`; height and width should be equal
* [x] Create `thumbnail-wd.jpg`; width should be >5x height
* [x] `hugodown::use_tidy_thumbnails()`
* [ ] Add intro sentence, e.g. the standard tagline for the package
* [ ] `usethis::use_tidy_thanks()`
-->

We're chuffed to announce the release of [haven](https://haven.tidyverse.org) 2.5.0. haven allows you to read and write SAS, SPSS, and Stata data formats from R, thanks to the wonderful [ReadStat](https://github.com/WizardMac/ReadStat) C library written by [Evan Miller](https://www.evanmiller.org/).

You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("haven")
```

The most important news for this release is that [Danny Smith](https://github.com/gorcha) is now a haven author in recognition of his significant and sustained contributions. He contributed the majority of improvements and bug fixes to this release.

Other improvements of note:

* You can set custom variable widths when writing by setting the `width` attribute of the variable.

* You can create FDA-compliant SAS transport files with haven, thanks to the addition of custom variable width support and some XPT writing related bug fixes.

* `write_dta()` now supports Stata's `StrL` variables. This means that it's possible to write Stata files containing strings longer than 2045 characters, which was previously a hard upper limit.

You can see a full list of changes in the [release notes](https://github.com/tidyverse/haven/blob/main/NEWS.md).

## Acknowledgements

A big thanks to all 24 folks who contributed to this released by filing issues or creating pull requests: [&#x0040;aito123](https://github.com/aito123), [&#x0040;arnaud-feldmann](https://github.com/arnaud-feldmann), [&#x0040;brianstamper](https://github.com/brianstamper), [&#x0040;dusadrian](https://github.com/dusadrian), [&#x0040;elimillera](https://github.com/elimillera), [&#x0040;etiennebacher](https://github.com/etiennebacher), [&#x0040;geebioso](https://github.com/geebioso), [&#x0040;gorcha](https://github.com/gorcha), [&#x0040;hadley](https://github.com/hadley), [&#x0040;jakoberr](https://github.com/jakoberr), [&#x0040;jennybc](https://github.com/jennybc), [&#x0040;juansebastianl](https://github.com/juansebastianl), [&#x0040;khanhhtt](https://github.com/khanhhtt), [&#x0040;Luke791](https://github.com/Luke791), [&#x0040;manhnguyen48](https://github.com/manhnguyen48), [&#x0040;maxecharel](https://github.com/maxecharel), [&#x0040;MokeEire](https://github.com/MokeEire), [&#x0040;Nate884](https://github.com/Nate884), [&#x0040;pskoulgi](https://github.com/pskoulgi), [&#x0040;Sama2than](https://github.com/Sama2than), [&#x0040;Shaunson26](https://github.com/Shaunson26), [&#x0040;sjkiss](https://github.com/sjkiss), [&#x0040;szimmer](https://github.com/szimmer), and [&#x0040;yangwenghou123](https://github.com/yangwenghou123). 
