---
output: hugodown::hugo_document

slug: usethis-2-0-0
title: usethis 2.0.0
date: 2020-12-10
author: Jennifer Bryan
description: >
    This is a big release aimed at improving usability, especially around Git
    and GitHub functionality.

photo:
  url: https://unsplash.com/photos/knzXwBCtEeM
  author: Kiana Bosman
categories: [package] 
tags: []
---

<!--
TODO:
* [ ] Pick category and tags (see existing with `post_tags()`)
* [ ] Find photo & update yaml metadata
* [ ] Create `thumbnail-sq.jpg`; height and width should be equal
* [ ] Create `thumbnail-wd.jpg`; width should be >5x height
* [ ] `hugodown::use_tidy_thumbnail()`
* [ ] Add intro sentence
* [ ] `use_tidy_thanks()`
-->

We're happy to announce the release of [usethis]({ home }) 1.9.0.9000. usethis is ... 

You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("{package}")
```

This blog post will ...

You can see a full list of changes in the [release notes]({ github_release })

```{r setup}
library(usethis)
```

## Topic 1

## Topic 2

## Acknowledgements

