---
title: {{ title }}
date: {{ date }}
author: {{ author }}
description: >
    A 2-3 sentence description of the post that appears on the articles page.
    This can be omitted if it would just recapitulate the title.

photo:
  url: https://unsplash.com/photos/n6vS3xlnsCc
  author: Kelley Bozarth

# one of: "deep-dive", "learn", "package", "programming", or "other"
categories: [package] 
tags: []
---

<!--
TODO:
* [ ] Pick category and tags (see existing with `post_tags()`)
* [ ] Find photo & update yaml metadata
* [ ] Create `thumbnail-sq.jpg`; height and width should be equal
* [ ] Create `thumbnail-wd.jpg`; width should be >5x height
* [ ] `hugodown::tidy_thumbnail()`
* [ ] `use_tidy_thanks("{{ github_org }}/{{ package }}")`
-->

We're {{ pleased }} to announce the release of [{{ package }}]({{ home }}) {{ version }}. {{ package }} is ... You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("{{package}}")
```

This blog post will ...

You can see a full list of changes in the [release notes]({{ github_release }})

```{r setup}
library({{package}})
```

## Topic 1

## Topic 2

## Acknowledgements

<!--
* `use_tidy_thanks("{{ github_org }}/{{ package }}")`
-->

