---
output: hugodown::hugo_document

slug: here-1-0-0
title: here 1.0.0 and rprojroot 2.0.1
date: 2020-11-15
author: Kirill Müller
description: >
    A 2-3 sentence description of the post that appears on the articles page.
    This can be omitted if it would just recapitulate the title.

photo:
  url: https://unsplash.com/photos/n6vS3xlnsCc
  author: Kelley Bozarth

# one of: "deep-dive", "learn", "package", "programming", or "other"
categories: [package] 
tags: []
---

<!--
TODO:
* [ ] Pick category and tags (see existing with `post_tags()`)
* [ ] Find photo & update yaml metadata
* [ ] Create `thumbnail-sq.jpg`; height and width should be equal
* [ ] Create `thumbnail-wd.jpg`; width should be >5x height
* [ ] `hugodown::use_tidy_thumbnail()`
* [ ] Add intro sentence
* [ ] `use_tidy_thanks()`
-->

We're chuffed to announce the release of [here]({ home }) 0.1.11.9002. here is ... 

You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("{package}")
```

This blog post will ...

You can see a full list of changes in the [release notes]({ github_release })

```{r setup}
library(here)
```

## Topic 1

## Topic 2

## Acknowledgements

