---
output: hugodown::hugo_document

slug: haven-2-2-0
title: haven 2.2.0
date: 2020-05-27
author: Hadley Wickham
description: >
    haven now uses vctrs which means labelled classes will be preserved in
    tidyr and dplyr operation.

photo:
  url: https://unsplash.com/photos/45GmTCcW8Hk
  author: Sergey Nikolaev

# one of: "deep-dive", "learn", "package", "programming", or "other"
categories: [package] 
tags: [haven]
---

<!--
TODO:
* [ ] `hugodown::tidy_thumbnail()`
* [ ] Add intro sentence
* [ ] `use_tidy_thanks()`
-->

We're tickled pink to announce the release of [haven](https://haven.tidyverse.org) 2.2.0. haven allows R to read and write SAS, SPSS, and Stata data formats by wrapping the [ReadStat](https://github.com/WizardMac/ReadStat) C library written by [Evan Miller](https://www.evanmiller.org/).

You can install haven from CRAN with:

```{r, eval = FALSE}
install.packages("haven")
```

This release includes

You can see a full list of changes in the [release notes](%7B%20github_release%20%7D)

```{r setup}
library(haven)
library(labelled)
```

## Acknowledgements
