---
output: hugodown::hugo_document

slug: reprex-2-0-0
title: reprex 2.0.0
date: 2021-04-02
author: Jenny Bryan
description: >
    reprex is now much easier to use on RStudio Server and RStudio Cloud.
photo:
  url: https://unsplash.com/photos/NROHA1B-NYk
  author: Mitchell Luo
categories: [package] 
---

<!--
* [ ] `usethis::use_tidy_thanks()`
-->

We're well pleased to announce the release of [reprex](https://reprex.tidyverse.org) 2.0.0.
reprex is ... 

You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("reprex")
```

This blog post will ...

You can see a full list of changes in the [release notes]({ github_release })

```{r setup}
library(reprex)
```

## Topic 1

## Topic 2

## Acknowledgements

10 contributors

[&#x0040;23ava](https://github.com/23ava), [&#x0040;jennybc](https://github.com/jennybc), [&#x0040;kiernann](https://github.com/kiernann), [&#x0040;krlmlr](https://github.com/krlmlr), [&#x0040;llrs](https://github.com/llrs), [&#x0040;MatthieuStigler](https://github.com/MatthieuStigler), [&#x0040;mcanouil](https://github.com/mcanouil), [&#x0040;MilesMcBain](https://github.com/MilesMcBain), [&#x0040;oharac](https://github.com/oharac), and [&#x0040;remlapmot](https://github.com/remlapmot).
