---
output: hugodown::hugo_document

slug: pkgdown-2-2-0
title: pkgdown 2.2.0
date: 2025-11-06
author: Hadley Wickham
description: >
    The latest version of pkgdown automatically builds markdown files that 
    make it easy for LLMs to use your website.

photo:
  url: https://unsplash.com/photos/cardboard-box-lot-fyaTq-fIlro
  author: CHUTTERSNAP

# one of: "deep-dive", "learn", "package", "programming", "roundup", or "other"
categories: [package] 
tags: [pkgdown]
---

<!--
TODO:
* [x] Look over / edit the post's title in the yaml
* [x] Edit (or delete) the description; note this appears in the Twitter card
* [x] Pick category and tags (see existing with `hugodown::tidy_show_meta()`)
* [x] Find photo & update yaml metadata
* [x] Create `thumbnail-sq.jpg`; height and width should be equal
* [x] Create `thumbnail-wd.jpg`; width should be >5x height
* [x] `hugodown::use_tidy_thumbnails()`
* [x] Add intro sentence, e.g. the standard tagline for the package
* [x] `usethis::use_tidy_thanks()`
-->

We're delighted to announce the release of [pkgdown](https://pkgdown.r-lib.org) 2.2.0. pkgdown is designed to make it quick and easy to build a beautiful and accessible website for your package.

You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("pkgdown")
```

This version of pkgdown has one major change: a new `pkgdown::build_llm_docs()` function that automatically creates files that make it easier for LLMs to read your documentation. Concretely, this means two things:

* You'll get an `llms.txt` at the root directory of your site. [`llms.txt`](https://llmstxt.org) is an emerging standard that  provides an easy way for an LLM to get an overview of your site. pkgdown creates an overview by combining your README, your function index, and your article index: this should give the LLM a broad overview of what your package does, along with links to find out more.

* Every existing `.html` on your site gets a corresponding `.md` file. These are generally easier for LLMs to understand because they contain just the content of the site, without any extraneous styling.

If you don't want to generate these files, just add the following to your `_pkgdown.yaml`:

```{yaml}
llm-docs: false
```

This release also includes new translations for Dutch and Japanese, removal of the long-deprecated `autolink_html()` and `preview_page()`, and a handful of other bug fixes and minor improvements. You can read about them all in the [release notes](https://github.com/r-lib/pkgdown/releases/tag/v2.2.0).

## Acknowledgements

As always, a big thanks to everyone who helped make this release possible: [&#x0040;cderv](https://github.com/cderv), [&#x0040;chabld](https://github.com/chabld), [&#x0040;Danny-dK](https://github.com/Danny-dK), [&#x0040;davidorme](https://github.com/davidorme), [&#x0040;dmurdoch](https://github.com/dmurdoch), [&#x0040;hadley](https://github.com/hadley), [&#x0040;hfrick](https://github.com/hfrick), [&#x0040;IndrajeetPatil](https://github.com/IndrajeetPatil), [&#x0040;jayhesselberth](https://github.com/jayhesselberth), [&#x0040;jeroenjanssens](https://github.com/jeroenjanssens), [&#x0040;jmgirard](https://github.com/jmgirard), [&#x0040;krlmlr](https://github.com/krlmlr), [&#x0040;lorenzwalthert](https://github.com/lorenzwalthert), [&#x0040;maelle](https://github.com/maelle), [&#x0040;MichaelChirico](https://github.com/MichaelChirico), [&#x0040;pepijn-devries](https://github.com/pepijn-devries), [&#x0040;remlapmot](https://github.com/remlapmot), [&#x0040;rempsyc](https://github.com/rempsyc), [&#x0040;Rohit-Satyam](https://github.com/Rohit-Satyam), [&#x0040;royfrancis](https://github.com/royfrancis), [&#x0040;rparmm](https://github.com/rparmm), [&#x0040;schloerke](https://github.com/schloerke), [&#x0040;TimTaylor](https://github.com/TimTaylor), and [&#x0040;usrbinr](https://github.com/usrbinr).
