---
output: hugodown::hugo_document

slug: tdd-2024
title: Tidyverse developer day 2024
date: 2024-04-04
author: Hadley Wickham
description: >
    Join the tidyverse team on August 15 

photo:
  author: JD Long
  url: https://cerebralmastication.com

# one of: "deep-dive", "learn", "package", "programming", "roundup", or "other"
categories: [package] 
tags: [tidyverse-dev-day]
---

```{=html}
<!--
TODO:
* [ ] Look over / edit the post's title in the yaml
* [ ] Edit (or delete) the description; note this appears in the Twitter card
* [ ] Pick category and tags (see existing with `hugodown::tidy_show_meta()`)
* [ ] Find photo & update yaml metadata
* [ ] Create `thumbnail-sq.jpg`; height and width should be equal
* [ ] Create `thumbnail-wd.jpg`; width should be >5x height
* [ ] `hugodown::use_tidy_thumbnails()`
* [ ] Add intro sentence, e.g. the standard tagline for the package
* [ ] `usethis::use_tidy_thanks()`
-->
```
It's been a hot minute since the last one, but we are very excited to announce that the next tidyverse developer day will be after [posit::conf](https://posit.co/conference/) in Seattle on August 15, 2024!

**What is the tidyverse developer day?** TDD is a day of learning and coding to nurture regular contributors to the tidyverse.
We'll provide food; you'll bring your laptop and enthusiasm.
The tidyverse team and other community helpers will be on hand to help you hit the ground running and/or get over any stumbling blocks that you encounter.
Don't have any ideas for something to work on?
No problem!
We'll be tagging issues in advance to make sure there's lots to do for any- and everyone, regardless of level of expertise.

**Who should attend?** Anyone who would like to get better at contributing to the tidyverse!
Everyone is welcome regardless of whether you've never done a PR before, or if you've already made your 10th package.
But you do need a ticket; to provide a fulfilling experience for all attendees we need to carefully manage the ratio of attendees to helpers.

**How much does it cost?** \$10.
This doesn't cover the costs of the event because we don't want to make attendance contingent on your ability to pay, but we've found some monetary commitment discourages people from taking tickets that they don't end up using.
But if the cost would prevent you from attending, please email [jenny\@posit.co](mailto:jenny@posit.co){.email} and we can figure something out.

[Buy your ticket now!](https://www.eventbrite.com/e/tidyverse-developer-day-2024-tickets-876018203027?aff=oddtdtcreator)
