---
output: hugodown::hugo_document

slug: nanoparquet-0-2-0
title: nanoparquet 0.2.0
date: 2024-05-30
author: Gábor Csárdi
description: >
    A 2-3 sentence description of the post that appears on the articles page.
    This can be omitted if it would just recapitulate the title.

photo:
  url: https://www.pexels.com/photo/clock-between-columns-20134435/
  author: Marina Zvada

# one of: "deep-dive", "learn", "package", "programming", "roundup", or "other"
categories: [package] 
tags: []
---

<!--
TODO:
* [ ] Look over / edit the post's title in the yaml
* [ ] Edit (or delete) the description; note this appears in the Twitter card
* [ ] Pick category and tags (see existing with `hugodown::tidy_show_meta()`)
* [ ] Find photo & update yaml metadata
* [ ] Create `thumbnail-sq.jpg`; height and width should be equal
* [ ] Create `thumbnail-wd.jpg`; width should be >5x height
* [ ] `hugodown::use_tidy_thumbnails()`
* [ ] Add intro sentence, e.g. the standard tagline for the package
* [ ] `usethis::use_tidy_thanks()`
-->

We're extremely pleased to announce the release of [nanoparquet](https://r-lib.github.io/nanoparquet/) 0.2.0. nanoparquet is ... 

You can install it from CRAN with:

```{r, eval = FALSE}
install.packages("nanoparquet")
```

This blog post will ...


```{r setup}
library(nanoparquet)
```

```{r include = FALSE}
library(pillar)
```

## What is Parquet?

<!--
- [ ] columnar
- [ ] binary
- [ ] rich types
- [ ] well supported
- [ ] performant
-->

## Why we created nanoparquet?

<!--
- [ ] encourage Parquet use for smaller data sets
- [ ] problems with other formats
-->

## Features

<!--
- [ ] lightweight
- [ ] common subset
- [ ] read and write
- [ ] support R's types well
- [ ] type maps
-->


## Limitations

<!--
- [ ] no nesting
- [ ] some types are not supported
- [ ] only Snappy compression
- [ ] no encryption
- [ ] slow-ish for large data sets
-->

Will fix soon:
<!--
- [ ] single row group
- [ ] no statistics, no checksum
- [ ] PLAIN encoding results larger files
-->

## Other tools for Parquet files

### In R

#### Apache Arrow


#### DuckDB


#### Othere (?): Spark? Impala?

### In Python

#### Apache Arrow

#### DuckDB + pandas

#### fastparquet

## Acknowledgements

<!--
- [ ] Hannes & DuckDB
- [ ] Arrow
- [ ] Google
-->
