---
title: "haven 1.1.2"
author: Mara Averick
date: '2018-06-28'
slug: haven-1-1-2
description: >
  haven 1.1.2 is now on CRAN.
categories:
  - package
photo:
  url: https://unsplash.com/photos/cLKDVvtoVZo
  author: Will van Wingerden
tags: []
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```


We are very pleased to announce the release of 
[haven](https://haven.tidyverse.org/) 1.1.2. haven allows R to read and write various data formats used by other statistical packages: SAS, SPSS, and STATA. Below, we highlight a few of the updates and fixes. For a complete list of 
changes, please see the [release notes](https://github.com/tidyverse/haven/blob/master/NEWS.md).

This version has improved handling for non-ASCII characters. haven can now
read and write non-ASCII paths in R 3.5, and `write_dta()` now allows non-ASCII
variable labels for Stata versions 14 and above.

`read_sav()` now accepts `.zsav` files; `.zsav` files can be written with `write_sav()` by setting `compress = TRUE`.

This release also incorporates updates from Evan Miller's [ReadStat](https://github.com/WizardMac/ReadStat) C library, including the 
ability to read and write Stata 15 files.

## Acknowledgements

Thank you to the 173 people who contributed issues, pull requests, and comments: [\@adeldaoud](https://github.com/adeldaoud), [\@afleishman](https://github.com/afleishman), [\@aftollefsen](https://github.com/aftollefsen), [\@aghaynes](https://github.com/aghaynes), [\@AHoerner](https://github.com/AHoerner), [\@ajdamico](https://github.com/ajdamico), [\@ajmazurie](https://github.com/ajmazurie), [\@akitepowell](https://github.com/akitepowell), [\@alawami](https://github.com/alawami), [\@alimanager](https://github.com/alimanager), [\@allitnils](https://github.com/allitnils), [\@AmyMikhail](https://github.com/AmyMikhail), [\@andrewheiss](https://github.com/andrewheiss), [\@anhqle](https://github.com/anhqle), [\@annennenne](https://github.com/annennenne), [\@anoopxaviour](https://github.com/anoopxaviour), [\@aszalucha](https://github.com/aszalucha), [\@austensen](https://github.com/austensen), [\@avallecam](https://github.com/avallecam), [\@awmercer](https://github.com/awmercer), [\@bamonroe](https://github.com/bamonroe), [\@batpigandme](https://github.com/batpigandme), [\@beamgau](https://github.com/beamgau), [\@beew](https://github.com/beew), [\@behrman](https://github.com/behrman), [\@BERENZ](https://github.com/BERENZ), [\@bethatkinson](https://github.com/bethatkinson), [\@billdenney](https://github.com/billdenney), [\@BobMuenchen](https://github.com/BobMuenchen), [\@BobTheScientist](https://github.com/BobTheScientist), [\@brianstamper](https://github.com/brianstamper), [\@BurninLeo](https://github.com/BurninLeo), [\@byandell](https://github.com/byandell), [\@carlganz](https://github.com/carlganz), [\@christophergandrud](https://github.com/christophergandrud), [\@cimentadaj](https://github.com/cimentadaj), [\@connorp](https://github.com/connorp), [\@crsh](https://github.com/crsh), [\@d4ff](https://github.com/d4ff), [\@dalewsteele](https://github.com/dalewsteele), [\@danhalligan](https://github.com/danhalligan), [\@davidjones-spartan](https://github.com/davidjones-spartan), [\@dbcuervo](https://github.com/dbcuervo), [\@dcava](https://github.com/dcava), [\@dchiu911](https://github.com/dchiu911), [\@Deleetdk](https://github.com/Deleetdk), [\@dennisfisher](https://github.com/dennisfisher), [\@dgromer](https://github.com/dgromer), [\@diogocp](https://github.com/diogocp), [\@DiogoFerrari](https://github.com/DiogoFerrari), [\@DominikMueller64](https://github.com/DominikMueller64), [\@donlelek](https://github.com/donlelek), [\@dramage1](https://github.com/dramage1), [\@drkamarul](https://github.com/drkamarul), [\@dsself](https://github.com/dsself), [\@dusadrian](https://github.com/dusadrian), [\@eborbath](https://github.com/eborbath), [\@ecortens](https://github.com/ecortens), [\@eddelbuettel](https://github.com/eddelbuettel), [\@ekstroem](https://github.com/ekstroem), [\@Enrico-Palazzo](https://github.com/Enrico-Palazzo), [\@evanmiller](https://github.com/evanmiller), [\@ewenharrison](https://github.com/ewenharrison), [\@eXcuvator](https://github.com/eXcuvator), [\@fhollenbach](https://github.com/fhollenbach), [\@filipwastberg](https://github.com/filipwastberg), [\@flaneuse](https://github.com/flaneuse), [\@fmerhout](https://github.com/fmerhout), [\@frankcsliu](https://github.com/frankcsliu), [\@g3o2](https://github.com/g3o2), [\@gabrakadabra](https://github.com/gabrakadabra), [\@gbiele](https://github.com/gbiele), [\@GeoBer](https://github.com/GeoBer), [\@gergness](https://github.com/gergness), [\@ghost](https://github.com/ghost), [\@gitrman](https://github.com/gitrman), [\@gorcha](https://github.com/gorcha), [\@h2appy](https://github.com/h2appy), [\@hadley](https://github.com/hadley), [\@HanjoStudy](https://github.com/HanjoStudy), [\@harrysouthworth](https://github.com/harrysouthworth), [\@huashan](https://github.com/huashan), [\@huftis](https://github.com/huftis), [\@imanuelcostigan](https://github.com/imanuelcostigan), [\@itsdalmo](https://github.com/itsdalmo), [\@izahn](https://github.com/izahn), [\@jandraor](https://github.com/jandraor), [\@JanMarvin](https://github.com/JanMarvin), [\@jaohar](https://github.com/jaohar), [\@jdjohn215](https://github.com/jdjohn215), [\@jemus42](https://github.com/jemus42), [\@jeremiahsb](https://github.com/jeremiahsb), [\@Jiang-Li](https://github.com/Jiang-Li), [\@jjchern](https://github.com/jjchern), [\@JKPeck](https://github.com/JKPeck), [\@jlegewie](https://github.com/jlegewie), [\@jllipatz](https://github.com/jllipatz), [\@jmurray1022](https://github.com/jmurray1022), [\@johngoldin](https://github.com/johngoldin), [\@jon-mellon](https://github.com/jon-mellon), [\@joshash](https://github.com/joshash), [\@jtchittenden](https://github.com/jtchittenden), [\@karldw](https://github.com/karldw), [\@kendonB](https://github.com/kendonB), [\@kkumari1](https://github.com/kkumari1), [\@krlmlr](https://github.com/krlmlr), [\@kuriwaki](https://github.com/kuriwaki), [\@kwenzig](https://github.com/kwenzig), [\@larmarange](https://github.com/larmarange), [\@leeper](https://github.com/leeper), [\@lepennec](https://github.com/lepennec), [\@lionel-](https://github.com/lionel-), [\@lucasmation](https://github.com/lucasmation), [\@m-dinardo](https://github.com/m-dinardo), [\@m-sostero](https://github.com/m-sostero), [\@marciz](https://github.com/marciz), [\@mariev](https://github.com/mariev), [\@mariusbarth](https://github.com/mariusbarth), [\@markriseley](https://github.com/markriseley), [\@mbojan](https://github.com/mbojan), [\@methodds](https://github.com/methodds), [\@mfansler](https://github.com/mfansler), [\@MichaelChirico](https://github.com/MichaelChirico), [\@michaelwhammer](https://github.com/michaelwhammer), [\@mikmart](https://github.com/mikmart), [\@mlaviolet](https://github.com/mlaviolet), [\@ncdingari](https://github.com/ncdingari), [\@nickbloom](https://github.com/nickbloom), [\@NilsEnevoldsen](https://github.com/NilsEnevoldsen), [\@njanetos](https://github.com/njanetos), [\@NoahMarconi](https://github.com/NoahMarconi), [\@nunsuch123](https://github.com/nunsuch123), [\@otoomet](https://github.com/otoomet), [\@pkq](https://github.com/pkq), [\@Plebejer](https://github.com/Plebejer), [\@prashantj](https://github.com/prashantj), [\@protogeezer](https://github.com/protogeezer), [\@rbirkelbach](https://github.com/rbirkelbach), [\@reikoch](https://github.com/reikoch), [\@rgayler](https://github.com/rgayler), [\@Rnngmk](https://github.com/Rnngmk), [\@robkar](https://github.com/robkar), [\@rogerjdeangelis](https://github.com/rogerjdeangelis), [\@rpruim](https://github.com/rpruim), [\@rubenarslan](https://github.com/rubenarslan), [\@salim-b](https://github.com/salim-b), [\@sargdavid](https://github.com/sargdavid), [\@sasutils](https://github.com/sasutils), [\@sfirke](https://github.com/sfirke), [\@sjkiss](https://github.com/sjkiss), [\@sjpierce](https://github.com/sjpierce), [\@sjPlot](https://github.com/sjPlot), [\@skanskan](https://github.com/skanskan), [\@statsccpr](https://github.com/statsccpr), [\@stefanmr](https://github.com/stefanmr), [\@steveniorfa](https://github.com/steveniorfa), [\@strengejacke](https://github.com/strengejacke), [\@stupersyn](https://github.com/stupersyn), [\@the-knife](https://github.com/the-knife), [\@thomasjwood](https://github.com/thomasjwood), [\@tidyx](https://github.com/tidyx), [\@tklebel](https://github.com/tklebel), [\@TUFFERST](https://github.com/TUFFERST), [\@tzoltak](https://github.com/tzoltak), [\@vate01](https://github.com/vate01), [\@vinhdizzo](https://github.com/vinhdizzo), [\@wbuchanan](https://github.com/wbuchanan), [\@wds15](https://github.com/wds15), [\@wepelham3](https://github.com/wepelham3), [\@withr](https://github.com/withr), [\@xinluwang](https://github.com/xinluwang), [\@yimingli](https://github.com/yimingli), and [\@yonicd](https://github.com/yonicd).
