---
output: hugodown::hugo_document

slug: pkgdown-1-6-0
title: pkgdown 1.6.0
date: 2020-09-12
author: Hadley Wickham
description: >
    This release mostly contains bug fixes and minor improvements, but
    it now uses the downlit and ragg packages for syntax highlighting and
    graphical output, respectively.

photo:
  url: https://unsplash.com/photos/GOQ32dlahDk
  author: Vitor Santos

# one of: "deep-dive", "learn", "package", "programming", or "other"
categories: [package] 
tags: [pkgdown]
---

We're stoked to announce the release of [pkgdown](%7B%20home%20%7D) 1.6.0.
pkgdown is designed to make it quick and easy to build a website for your package.
Install it with:

```{r, eval = FALSE}
install.packages("pkgdown")
```

This release mostly contains a bunch of minor improvements and bug fixes that you can read about in the [release notes](https://pkgdown.r-lib.org/news/index.html#pkgdown-1-6-0-2020-09-07).
But there are two major changes:

-   The syntax highlighing and autolinking is now powered by the new [downlit](https://downlit.r-lib.org) package.
    There should be very little change in behaviour because the code in downlit was extracted from pkgdown, but this will make it easier to use pkgdown's nice linking/highlighting in more places.

-   pkgdown now uses the [ragg](https://ragg.r-lib.org) package for graphical output in examples.
    This should be a little faster and will produce higher quality output that's the same on every operating systems.

## Thanks!

A big thanks to all 55 contributors who helped make this release possible with their bug reports, thoughtful discussion, and code contributions: [&#x0040;Anirban166](https://github.com/Anirban166), [&#x0040;batpigandme](https://github.com/batpigandme), [&#x0040;bblodfon](https://github.com/bblodfon), [&#x0040;benjaminleroy](https://github.com/benjaminleroy), [&#x0040;cderv](https://github.com/cderv), [&#x0040;chuxinyuan](https://github.com/chuxinyuan), [&#x0040;DanChaltiel](https://github.com/DanChaltiel), [&#x0040;dankelley](https://github.com/dankelley), [&#x0040;davidchall](https://github.com/davidchall), [&#x0040;davidhodge931](https://github.com/davidhodge931), [&#x0040;DavisVaughan](https://github.com/DavisVaughan), [&#x0040;dfsnow](https://github.com/dfsnow), [&#x0040;donaldRwilliams](https://github.com/donaldRwilliams), [&#x0040;Eluvias](https://github.com/Eluvias), [&#x0040;erhla](https://github.com/erhla), [&#x0040;fmmattioni](https://github.com/fmmattioni), [&#x0040;GegznaV](https://github.com/GegznaV), [&#x0040;GregorDeCillia](https://github.com/GregorDeCillia), [&#x0040;gustavdelius](https://github.com/gustavdelius), [&#x0040;hadley](https://github.com/hadley), [&#x0040;hbaniecki](https://github.com/hbaniecki), [&#x0040;jameslamb](https://github.com/jameslamb), [&#x0040;jayhesselberth](https://github.com/jayhesselberth), [&#x0040;jeffwong-nflx](https://github.com/jeffwong-nflx), [&#x0040;jennybc](https://github.com/jennybc), [&#x0040;jonkeane](https://github.com/jonkeane), [&#x0040;jranke](https://github.com/jranke), [&#x0040;kevinushey](https://github.com/kevinushey), [&#x0040;klmr](https://github.com/klmr), [&#x0040;krlmlr](https://github.com/krlmlr), [&#x0040;lcolladotor](https://github.com/lcolladotor), [&#x0040;maelle](https://github.com/maelle), [&#x0040;maxheld83](https://github.com/maxheld83), [&#x0040;mladenjovanovic](https://github.com/mladenjovanovic), [&#x0040;ms609](https://github.com/ms609), [&#x0040;mstr3336](https://github.com/mstr3336), [&#x0040;ngreifer](https://github.com/ngreifer), [&#x0040;OceaneCsn](https://github.com/OceaneCsn), [&#x0040;padpadpadpad](https://github.com/padpadpadpad), [&#x0040;pat-s](https://github.com/pat-s), [&#x0040;paulponcet](https://github.com/paulponcet), [&#x0040;ramiromagno](https://github.com/ramiromagno), [&#x0040;randy3k](https://github.com/randy3k), [&#x0040;rickhelmus](https://github.com/rickhelmus), [&#x0040;royfrancis](https://github.com/royfrancis), [&#x0040;schloerke](https://github.com/schloerke), [&#x0040;statnmap](https://github.com/statnmap), [&#x0040;stefanoborini](https://github.com/stefanoborini), [&#x0040;tanho63](https://github.com/tanho63), [&#x0040;ThierryO](https://github.com/ThierryO), [&#x0040;thomas-neitmann](https://github.com/thomas-neitmann), [&#x0040;ttimbers](https://github.com/ttimbers), [&#x0040;wkmor1](https://github.com/wkmor1), [&#x0040;zeileis](https://github.com/zeileis), and [&#x0040;zkamvar](https://github.com/zkamvar).
